package sensorPH;


/**
* sensorPH/SensorPHOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorPH.idl
* Sexta-feira, 27 de Março de 2015 22h54min24s BRT
*/

public interface SensorPHOperations 
{
  void alterarPH (float ph);
} // interface SensorPHOperations
