package sensorPH;


/**
* sensorPH/SensorPHHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorPH.idl
* Sexta-feira, 27 de Março de 2015 22h54min24s BRT
*/

abstract public class SensorPHHelper
{
  private static String  _id = "IDL:sensorPH/SensorPH:1.0";

  public static void insert (org.omg.CORBA.Any a, sensorPH.SensorPH that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sensorPH.SensorPH extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sensorPH.SensorPHHelper.id (), "SensorPH");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sensorPH.SensorPH read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SensorPHStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sensorPH.SensorPH value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sensorPH.SensorPH narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sensorPH.SensorPH)
      return (sensorPH.SensorPH)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sensorPH._SensorPHStub stub = new sensorPH._SensorPHStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sensorPH.SensorPH unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sensorPH.SensorPH)
      return (sensorPH.SensorPH)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sensorPH._SensorPHStub stub = new sensorPH._SensorPHStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
