package sensorCor;


/**
* sensorCor/SensorCorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorCor.idl
* Sexta-feira, 27 de Março de 2015 22h54min04s BRT
*/

public interface SensorCorOperations 
{
  void alterarCor (float cor);
} // interface SensorCorOperations
