package sensorPH;


/**
* sensorPH/SensorPH.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorPH.idl
* Sexta-feira, 27 de Março de 2015 13h53min40s BRT
*/

public interface SensorPH extends SensorPHOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SensorPH
