package sensorTemperatura;


/**
* sensorTemperatura/SensorTemperaturaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorTemperatura.idl
* Sexta-feira, 27 de Março de 2015 13h53min45s BRT
*/

public interface SensorTemperaturaOperations 
{
  void alterarTemperatura (float temperatura);
} // interface SensorTemperaturaOperations
