package daemonGUI;


/**
* daemonGUI/DaemonGUIHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DaemonGUI.idl
* Sexta-feira, 27 de Março de 2015 22h53min48s BRT
*/

abstract public class DaemonGUIHelper
{
  private static String  _id = "IDL:daemonGUI/DaemonGUI:1.0";

  public static void insert (org.omg.CORBA.Any a, daemonGUI.DaemonGUI that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static daemonGUI.DaemonGUI extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (daemonGUI.DaemonGUIHelper.id (), "DaemonGUI");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static daemonGUI.DaemonGUI read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DaemonGUIStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, daemonGUI.DaemonGUI value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static daemonGUI.DaemonGUI narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof daemonGUI.DaemonGUI)
      return (daemonGUI.DaemonGUI)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      daemonGUI._DaemonGUIStub stub = new daemonGUI._DaemonGUIStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static daemonGUI.DaemonGUI unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof daemonGUI.DaemonGUI)
      return (daemonGUI.DaemonGUI)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      daemonGUI._DaemonGUIStub stub = new daemonGUI._DaemonGUIStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
