package daemonGUI;


/**
* daemonGUI/DaemonGUIOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DaemonGUI.idl
* Sexta-feira, 27 de Março de 2015 22h53min48s BRT
*/

public interface DaemonGUIOperations 
{
  void notificarGui (String notificacaoID, String notificacao);
} // interface DaemonGUIOperations
