package daemonGUI;


/**
* daemonGUI/DaemonGUI.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DaemonGUI.idl
* Sexta-feira, 27 de Março de 2015 22h53min48s BRT
*/

public interface DaemonGUI extends DaemonGUIOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DaemonGUI
