package daemonGUI;

/**
* daemonGUI/DaemonGUIHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DaemonGUI.idl
* Sexta-feira, 27 de Março de 2015 22h53min48s BRT
*/

public final class DaemonGUIHolder implements org.omg.CORBA.portable.Streamable
{
  public daemonGUI.DaemonGUI value = null;

  public DaemonGUIHolder ()
  {
  }

  public DaemonGUIHolder (daemonGUI.DaemonGUI initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = daemonGUI.DaemonGUIHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    daemonGUI.DaemonGUIHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return daemonGUI.DaemonGUIHelper.type ();
  }

}
