package sensorCor;


/**
* sensorCor/SensorCorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorCor.idl
* Sexta-feira, 27 de Março de 2015 13h53min33s BRT
*/

abstract public class SensorCorHelper
{
  private static String  _id = "IDL:sensorCor/SensorCor:1.0";

  public static void insert (org.omg.CORBA.Any a, sensorCor.SensorCor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sensorCor.SensorCor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sensorCor.SensorCorHelper.id (), "SensorCor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sensorCor.SensorCor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SensorCorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sensorCor.SensorCor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sensorCor.SensorCor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sensorCor.SensorCor)
      return (sensorCor.SensorCor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sensorCor._SensorCorStub stub = new sensorCor._SensorCorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sensorCor.SensorCor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sensorCor.SensorCor)
      return (sensorCor.SensorCor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sensorCor._SensorCorStub stub = new sensorCor._SensorCorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
