package sensorCor;


/**
* sensorCor/SensorCor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorCor.idl
* Sexta-feira, 27 de Março de 2015 13h53min33s BRT
*/

public interface SensorCor extends SensorCorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SensorCor
