package clientDaemon;


/**
* clientDaemon/_ClientDaemonStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientDaemon.idl
* Sexta-feira, 27 de Março de 2015 13h53min26s BRT
*/

public class _ClientDaemonStub extends org.omg.CORBA.portable.ObjectImpl implements clientDaemon.ClientDaemon
{

  public void notificarGui (String notificacaoID, String notificacao)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notificarGui", true);
                $out.write_string (notificacaoID);
                $out.write_string (notificacao);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notificarGui (notificacaoID, notificacao        );
            } finally {
                _releaseReply ($in);
            }
  } // notificarGui

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:clientDaemon/ClientDaemon:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ClientDaemonStub
