package clientDaemon;


/**
* clientDaemon/ClientDaemonOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientDaemon.idl
* Sexta-feira, 27 de Março de 2015 13h53min26s BRT
*/

public interface ClientDaemonOperations 
{
  void notificarGui (String notificacaoID, String notificacao);
} // interface ClientDaemonOperations
