package clientDaemon;


/**
* clientDaemon/ClientDaemon.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientDaemon.idl
* Sexta-feira, 27 de Março de 2015 13h53min26s BRT
*/

public interface ClientDaemon extends ClientDaemonOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientDaemon
