package clientDaemon;


/**
* clientDaemon/ClientDaemonHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientDaemon.idl
* Sexta-feira, 27 de Março de 2015 13h53min26s BRT
*/

abstract public class ClientDaemonHelper
{
  private static String  _id = "IDL:clientDaemon/ClientDaemon:1.0";

  public static void insert (org.omg.CORBA.Any a, clientDaemon.ClientDaemon that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static clientDaemon.ClientDaemon extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (clientDaemon.ClientDaemonHelper.id (), "ClientDaemon");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static clientDaemon.ClientDaemon read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientDaemonStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, clientDaemon.ClientDaemon value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static clientDaemon.ClientDaemon narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof clientDaemon.ClientDaemon)
      return (clientDaemon.ClientDaemon)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      clientDaemon._ClientDaemonStub stub = new clientDaemon._ClientDaemonStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static clientDaemon.ClientDaemon unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof clientDaemon.ClientDaemon)
      return (clientDaemon.ClientDaemon)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      clientDaemon._ClientDaemonStub stub = new clientDaemon._ClientDaemonStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
