package clientDaemon;

/**
* clientDaemon/ClientDaemonHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientDaemon.idl
* Sexta-feira, 27 de Março de 2015 13h53min26s BRT
*/

public final class ClientDaemonHolder implements org.omg.CORBA.portable.Streamable
{
  public clientDaemon.ClientDaemon value = null;

  public ClientDaemonHolder ()
  {
  }

  public ClientDaemonHolder (clientDaemon.ClientDaemon initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = clientDaemon.ClientDaemonHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    clientDaemon.ClientDaemonHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return clientDaemon.ClientDaemonHelper.type ();
  }

}
