package sensorTemperatura;


/**
* sensorTemperatura/SensorTemperatura.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorTemperatura.idl
* Sexta-feira, 27 de Março de 2015 22h54min55s BRT
*/

public interface SensorTemperatura extends SensorTemperaturaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SensorTemperatura
